@host = localhost
@port = 4000
POST http://{{host}}:{{port}}/auth/register
content-type: application/json

{
    "username": "RangerRick",
    "email": "ranger@rick.com",
    "password": "Password123!",
    "role": "admin"
}

###

POST http://{{host}}:{{port}}/auth/register
content-type: application/json

{
    "username": "GraniteChicken",
    "email": "granite@chicken.com",
    "password": "Password123!"
}

###

POST http://{{host}}:{{port}}/auth/login
content-type: application/json

{
    "email" : "granite@chicken.com",
    "password": "Password123!"
}

###

POST http://{{host}}:{{port}}/auth/register
content-type: application/json

{
    "username": "LimestoneFish",
    "email": "limestone@fish.com",
    "password": "Password123!"
}

###

POST http://{{host}}:{{port}}/auth/login
content-type: application/json

{
    "email" : "limestone@fish.com",
    "password": "Password123!"
}

###

GET http://{{host}}:{{port}}/admin