@host = localhost
@port = 4000
POST http://{{host}}:{{port}}/auth/register
content-type: application/json

{
    "username": "RangerRick",
    "email": "ranger@rick.com",
    "password": "Password123!",
    "role": "admin"
}

###

POST http://{{host}}:{{port}}/auth/login
content-type: application/json

{
    "email" : "ranger@rick.com",
    "password": "Password123!"
}

###

GET http://{{host}}:{{port}}/admin
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2IzNmE5OTdiYWE1MTcxNTVmOGYxMSIsImlhdCI6MTcxOTQ5OTYzMiwiZXhwIjoxNzE5NTg2MDMyfQ.kbxxWopti9aHkLwXVKYBY3uaeE-LYAMAEpMEjVvBzt8
###

POST http://{{host}}:{{port}}/auth/register
content-type: application/json

{
    "username": "GraniteChicken",
    "email": "granite@chicken.com",
    "password": "Password123!"
}

###

POST http://{{host}}:{{port}}/auth/login
content-type: application/json

{
    "email" : "granite@chicken.com",
    "password": "Password123!"
}

###

POST http://{{host}}:{{port}}/auth/register
content-type: application/json

{
    "username": "LimestoneFish",
    "email": "limestone@fish.com",
    "password": "Password123!"
}

###

POST http://{{host}}:{{port}}/auth/login
content-type: application/json

{
    "email" : "limestone@fish.com",
    "password": "Password123!"
}

###
POST http://localhost:4000/adventures
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2Q2NmFiMTlhYjI0NDFiZDc2OWYxZCIsImlhdCI6MTcxOTY4NDk0MCwiZXhwIjoxNzE5NzcxMzQwfQ.Jfhiuae9Bmc4QeIcdai_-PelhM8q_hlQohF7MAv5Vsc
Content-Type: application/json

{
    "name": "Walking into Mordor",
    "description": "po-tay-toes",
    "userId": "667d66ab19ab2441bd769f1d"
}

###